In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [2]:
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [3]:
one_hot("amazing restaurant",30)

[18, 14]

In [4]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[13, 16], [18, 14], [19, 11], [22, 13, 21], [7, 13, 10], [6, 16], [3, 13, 18], [14, 14], [14, 8], [4, 22]]


In [5]:
max_length = 4
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[13 16  0  0]
 [18 14  0  0]
 [19 11  0  0]
 [22 13 21  0]
 [ 7 13 10  0]
 [ 6 16  0  0]
 [ 3 13 18  0]
 [14 14  0  0]
 [14  8  0  0]
 [ 4 22  0  0]]


In [6]:
embeded_vector_size = 5

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [7]:
X = padded_reviews
y = sentiment

In [8]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 4, 5)              150       
                                                                 
 flatten (Flatten)           (None, 20)                0         
                                                                 
 dense (Dense)               (None, 1)                 21        
                                                                 
Total params: 171 (684.00 Byte)
Trainable params: 171 (684.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [9]:
model.fit(X, y, epochs=50, verbose=0)

In [10]:
# evaluate the model
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 [==============================] - 0s 192ms/step - loss: 0.6325 - accuracy: 1.0000


1.0

In [11]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [12]:
weights[13]

array([ 0.0669826 , -0.09640061, -0.05116435,  0.08272383,  0.06365374],
      dtype=float32)

In [13]:
weights[4]

array([-0.07996269,  0.02305521, -0.10200935, -0.05872885, -0.01090406],
      dtype=float32)

In [14]:
weights[16]

array([-0.03348647, -0.03511249,  0.00246832, -0.01095042,  0.01280099],
      dtype=float32)