In [1]:
import numpy as np

# Calculating Profit / Loss from revenue and expances 

In [2]:
revenue = np.array([[120,80,90],[100,110,95],[110,100,80]])
expances = np.array([[100,60,80],[70,90,80],[100,80,70]])

In [3]:
profit = revenue - expances
profit

array([[20, 20, 10],
       [30, 20, 15],
       [10, 20, 10]])

# Calculate total sales from units and price per unit using matrix multiplication

In [4]:
price_per_unit = np.array([1000,900,1200])
units = np.array([[30,40,50],[5,10,15],[2,5,7]])

In [5]:
price_per_unit*units

array([[30000, 36000, 60000],
       [ 5000,  9000, 18000],
       [ 2000,  4500,  8400]])

In [6]:
np.dot(price_per_unit, units)

array([36900, 55000, 71900])

# Exercise

In [7]:
reliance = np.array([200,220,250])
infosys = np.array([68,79,105])
tcs = np.array([110,140,180])
wipro = np.array([80,85,90])

In [8]:
revenue = np.array([[200,220,250],[68,79,105],[110,140,180],[80,85,90]])
revenue*75

array([[15000, 16500, 18750],
       [ 5100,  5925,  7875],
       [ 8250, 10500, 13500],
       [ 6000,  6375,  6750]])

In [9]:
units_sold = np.array([[50,60,25],[10,13,5],[40,70,52]])
price_per_unit = np.array([20,30,15])

In [10]:
total_sales = price_per_unit*units_sold
total_sales

array([[1000, 1800,  375],
       [ 200,  390,   75],
       [ 800, 2100,  780]])

In [11]:
np.dot(units_sold, price_per_unit)

array([3175,  665, 3680])